version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /pythonapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /pythonapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /pythonapp/docker-credentials/docker_registry_url
  
phases:
  install:
    runtime-versions:
      python : 3.11
      
  pre_build:
    commands:
      - "pip install -r requirements.txt"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      
  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t "sample-python-flask-service-demo:latest" .
      - docker tag "sample-python-flask-service-demo:latest" "$DOCKER_REGISTRY_USERNAME/sample-python-flask-service-demo:latest"
      - docker push "$DOCKER_REGISTRY_USERNAME/sample-python-flask-service-demo:latest"
    
  post_build:
    commands:
      - echo "Build is done Sagar Wadhwa !!"
